version: "3.12"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.3.2
    command: >
      mlflow server
      --host 0.0.0.0 --port ${MLFLOW_SERVICE_PORT}
      --backend-store-uri sqlite:////mlflowdb/mlflow.db
      --serve-artifacts
      --artifacts-destination file:///mlartifacts
    ports: ["${LOCAL_PORT}:${MLFLOW_SERVICE_PORT}"]
    volumes:
      - mlflowdb:/mlflowdb
      - mlartifacts:/mlartifacts
 
  model-trainer:
      build:
        context: ./model-trainer
      image: model-trainer:latest
      environment:
        - MLFLOW_TRACKING_URI=http://mlflow:${MLFLOW_SERVICE_PORT}
      depends_on: [mlflow]

volumes:
  mlflowdb:
  mlartifacts:

