[project]
name = "router-api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.111",
  "uvicorn[standard]>=0.29",
  "httpx>=0.27",
  "docker>=7.0",
  "mlflow>=2.15", # to resolve aliases & download artifacts if needed
  "caddy>=1.3.2",
]
