FROM python:3.12-slim

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

RUN pip install --no-cache-dir \
    "mlflow[extras]==3.3.1" \
    "torch>=2.8.0"

ENV PYTHONUNBUFFERED=1
ENV SERVE_PORT=8080
EXPOSE 8080

CMD mlflow models serve -m "${SERVE_MODEL_URI}" \
    -h 0.0.0.0 -p "${SERVE_PORT}" --workers "${MLFLOW_MODELS_WORKERS:-2}" \
    --env-manager local
