FROM python:3.12-slim

RUN python -m pip install --no-cache-dir --upgrade pip setuptools wheel

WORKDIR /app

COPY pyproject.toml ./
RUN pip install --no-cache-dir \
    "mlflow==3.3.1" \
    "numpy>=2.3.2" \
    "pandas>=2.3.0" \
    "torch>=2.8.0"
    "scikit-learn>=1.7.1"

COPY src/ .
COPY demo_data/ ./demo_data/

ENTRYPOINT ["python", "/app/train.py"]
