sklearn-model-1:
  trainer_image: trainer-sklearn-model-1:latest
  timeout: 1800
  env:
    MLFLOW_EXPERIMENT: diabetes_rf_demo
    REGISTER_MODEL_NAME: DiabetesRF
    N_ESTIMATORS: "200"
    MAX_DEPTH: "8"