# model-images/Dockerfile
FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:0.8.11 /uv /uvx /bin/
ENV UV_SYSTEM_PYTHON=1 UV_LINK_MODE=copy \
    PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

WORKDIR /app


COPY model-images/sklearn-model-1/pyproject.toml model-images/sklearn-model-1/uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-install-project

ENV PATH="/app/.venv/bin:$PATH"

COPY model-images/sklearn-model-1/src/ .
COPY demo_data/ ./demo_data/

ENTRYPOINT ["python","/app/train.py"]
