[project]
name = "model-images"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mlflow>=3.3.1",
    "numpy>=2.3.2",
    "scikit-learn>=1.7.1",
    "shap>=0.48.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.12",
]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["F401"]
